<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '',
  'APP_SHARE_DIR' => 'var/share',
  'DEFAULT_URI' => 'http://localhost',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/archon_crm?serverVersion=8.0',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '05384ca8f31604be8648b8c350e561444b6c149e319bf7f7c8f23b4e61a82dd7',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'null://null',
);
