[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.pdo",
  "php83Extensions.pdo_mysql",
  "php83Extensions.mbstring",
  "php83Extensions.openssl",
  "php83Extensions.tokenizer",
  "php83Extensions.xml",
  "php83Extensions.ctype",
  "php83Extensions.intl",
  "php83Extensions.sodium",
  "php83Extensions.curl",
  "php83Extensions.zip",
  "composer"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction --no-scripts"
]

[phases.build]
cmds = [
  "php bin/console cache:clear --env=prod --no-debug --no-warmup",
  "php bin/console cache:warmup --env=prod --no-debug"
]

[start]
cmd = "php bin/console doctrine:migrations:migrate --no-interaction --env=prod && php -S 0.0.0.0:$PORT -t public/"
